Add interview events, this will enables listeners to receive updates …
athombv/zigbee-shepherd pull request #11
Opened 2017-08-02 19:26 UTC by RobinBol

…on the progress of the join process

Sorry about the whitespace stuff, my editor fixes that by default, relevant code changes are:
- `lib/components/af.js`
- `lib/components/event_handlers.js` -> 117 - 145
- `lib/shepherd.js` -> 103 - 105

2017-08-03 12:56 UTC, jeroenvollenbrock requested changes

2017-08-03 12:56 UTC, jeroenvollenbrock commented on lib/components/af.js
> +af.zclClustersReq = function (dstEp, eventEmitter, callback) {    // callback(err, clusters)
please make the eventEmittter argument optional to avoid breaking existing code

2017-08-03 13:36 UTC, RobinBol commented on lib/components/af.js
> +af.zclClustersReq = function (dstEp, eventEmitter, callback) {    // callback(err, clusters)
Added a check, if eventEmitter is a function, consider it the callback and do not emit events.

2017-08-04 15:16 UTC, jeroenvollenbrock approved these changes

2017-08-04 15:16 UTC, merged